### ISSUE TITLE
Issue with crafting ban in 0.4.1

### ISSUE THREAD

**Issue by SnowBlitzz** [EpicBanItemTeam/EpicBanItem#54]
When crafting is banned for an object in previous version, it only blocks crafting that item - example: stick is banned from crafting, you can't craft a stick, but CAN use stick to craft other things like torch.

Now, using the same example, you can't use the stick to craft other things anymore which is probably not intended.

**Comment by SettingDust** [comment]
Fixed in [1.1.6](https://ore.spongepowered.org/EpicBanItem/EpicBanItem/versions/1.1.6)
